apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: proyecto2
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service   # Cuando no se especifica el tipo de servicio, por defecto es ClusterIP
metadata:
  namespace: proyecto2
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 #Puerto exéusto por el el servicio EN el cluster
      targetPort: 6379 #Puerto del contenedor
  type: ClusterIP