// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: client/publisher.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Publicador_PublicarKafka_FullMethodName = "/publisher.Publicador/PublicarKafka"
)

// PublicadorClient is the client API for Publicador service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicadorClient interface {
	PublicarKafka(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Respuesta, error)
}

type publicadorClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicadorClient(cc grpc.ClientConnInterface) PublicadorClient {
	return &publicadorClient{cc}
}

func (c *publicadorClient) PublicarKafka(ctx context.Context, in *Mensaje, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, Publicador_PublicarKafka_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicadorServer is the server API for Publicador service.
// All implementations must embed UnimplementedPublicadorServer
// for forward compatibility.
type PublicadorServer interface {
	PublicarKafka(context.Context, *Mensaje) (*Respuesta, error)
	mustEmbedUnimplementedPublicadorServer()
}

// UnimplementedPublicadorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicadorServer struct{}

func (UnimplementedPublicadorServer) PublicarKafka(context.Context, *Mensaje) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicarKafka not implemented")
}
func (UnimplementedPublicadorServer) mustEmbedUnimplementedPublicadorServer() {}
func (UnimplementedPublicadorServer) testEmbeddedByValue()                    {}

// UnsafePublicadorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicadorServer will
// result in compilation errors.
type UnsafePublicadorServer interface {
	mustEmbedUnimplementedPublicadorServer()
}

func RegisterPublicadorServer(s grpc.ServiceRegistrar, srv PublicadorServer) {
	// If the following call pancis, it indicates UnimplementedPublicadorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Publicador_ServiceDesc, srv)
}

func _Publicador_PublicarKafka_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mensaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicadorServer).PublicarKafka(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publicador_PublicarKafka_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicadorServer).PublicarKafka(ctx, req.(*Mensaje))
	}
	return interceptor(ctx, in, info, handler)
}

// Publicador_ServiceDesc is the grpc.ServiceDesc for Publicador service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Publicador_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "publisher.Publicador",
	HandlerType: (*PublicadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicarKafka",
			Handler:    _Publicador_PublicarKafka_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client/publisher.proto",
}
