apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: 34-173-10-108.sslip.io/sopes1p2/api-go:latest
        ports:
          - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  namespace: proyecto2
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8081         # Puerto interno del clúster
      targetPort: 8081   # Puerto expuesto por el contenedor
  type: ClusterIP
