// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: client/publisher.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mensaje struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contenido     string                 `protobuf:"bytes,1,opt,name=contenido,proto3" json:"contenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mensaje) Reset() {
	*x = Mensaje{}
	mi := &file_client_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensaje) ProtoMessage() {}

func (x *Mensaje) ProtoReflect() protoreflect.Message {
	mi := &file_client_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensaje.ProtoReflect.Descriptor instead.
func (*Mensaje) Descriptor() ([]byte, []int) {
	return file_client_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *Mensaje) GetContenido() string {
	if x != nil {
		return x.Contenido
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	mi := &file_client_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_client_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_client_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_client_publisher_proto protoreflect.FileDescriptor

const file_client_publisher_proto_rawDesc = "" +
	"\n" +
	"\x16client/publisher.proto\x12\tpublisher\"'\n" +
	"\aMensaje\x12\x1c\n" +
	"\tcontenido\x18\x01 \x01(\tR\tcontenido\"#\n" +
	"\tRespuesta\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado2\x83\x01\n" +
	"\n" +
	"Publicador\x12:\n" +
	"\x0ePublicarRabbit\x12\x12.publisher.Mensaje\x1a\x14.publisher.Respuesta\x129\n" +
	"\rPublicarKafka\x12\x12.publisher.Mensaje\x1a\x14.publisher.RespuestaB\x11Z\x0f./client;clientb\x06proto3"

var (
	file_client_publisher_proto_rawDescOnce sync.Once
	file_client_publisher_proto_rawDescData []byte
)

func file_client_publisher_proto_rawDescGZIP() []byte {
	file_client_publisher_proto_rawDescOnce.Do(func() {
		file_client_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_publisher_proto_rawDesc), len(file_client_publisher_proto_rawDesc)))
	})
	return file_client_publisher_proto_rawDescData
}

var file_client_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_publisher_proto_goTypes = []any{
	(*Mensaje)(nil),   // 0: publisher.Mensaje
	(*Respuesta)(nil), // 1: publisher.Respuesta
}
var file_client_publisher_proto_depIdxs = []int32{
	0, // 0: publisher.Publicador.PublicarRabbit:input_type -> publisher.Mensaje
	0, // 1: publisher.Publicador.PublicarKafka:input_type -> publisher.Mensaje
	1, // 2: publisher.Publicador.PublicarRabbit:output_type -> publisher.Respuesta
	1, // 3: publisher.Publicador.PublicarKafka:output_type -> publisher.Respuesta
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_publisher_proto_init() }
func file_client_publisher_proto_init() {
	if File_client_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_publisher_proto_rawDesc), len(file_client_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_publisher_proto_goTypes,
		DependencyIndexes: file_client_publisher_proto_depIdxs,
		MessageInfos:      file_client_publisher_proto_msgTypes,
	}.Build()
	File_client_publisher_proto = out.File
	file_client_publisher_proto_goTypes = nil
	file_client_publisher_proto_depIdxs = nil
}
